import './globals.css'
import type { Metadata } from 'next'
import { fontSans } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import { Providers } from '@/components/providers'
import { ThemeToggle } from '@/components/theme/toggle'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        "scroll-smooth transition-all duration-1000",
        "overflow-hidden",
        fontSans.variable
      )}>
        <Providers>
          <ThemeToggle className="" />
          {children}
        </Providers>
      </body>
    </html>
  )
}
